### ISSUE TITLE
Unavailability of the simulator of the fermentation process of the Saccharomyces cerevisiae cultivation

### ISSUE THREAD

**Issue by fabiocentofanti** [jogonmar/MVBatch#40]
It is not clear how to simulate new batches form the fermentation process of the Saccharomyces cerevisiae cultivation.
This feature is clearly stated as available in the description of the stable version and in the reference paper _MVbatch: a matlab toolbox for batch process modelling and monitoring_ González-Martínez et al. (2018).
If it is possible to simulate new batches from this process, it is not clear how.
Could you explain how simulate new batches?
Thank you

**Comment by jogonmar** [comment]
In the latest update (both release and branch in the repository), you will find a new folder called "simulator". In order to simulate NOC batch data, you only need to execute the script "simule". The script is self-explanatory and you will be able to identify the cell arrays containing NOC and faulty batches. Enjoy.
